version: '3.2'

# Définition des services docker
services:
    # Ces services comprennent un serveur todo, un client, et un superviseur qui observe les tâches
    c1:
      # Client - Ajoute et retire des tâches automatiquement
      image: arret02-client
      container_name: arret02-c1
      build: './client'
      tty: true
      volumes:
      - "./fortune:/fortune"
      
    s1:
      # Serveur - Traite les demandes todo
      image: arret02-serveur
      container_name: arret02-s1
      build: './serveur'
      tty: true
      volumes:
        - "./fortune:/fortune"

    gestionnaire:
      # Permet d'observer les tâches en cours
      image: arret02-gestionnaire
      container_name: arret02-gestionnaire
      build: './gestionnaire'
      tty: true
      volumes:
      - "./fortune:/fortune"
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1'

# Réseau par défaut
networks:
  arret02-todo-net:
    driver: bridge