version: '3.2'

services:
  # Premier client - Ajoute et retire des tâches automatiquement
  c1:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: arret05-c1
    image: arret05-client
    depends_on:
      - s1
    environment:
      - MONSERVEUR='s1'
      - MONNOM='c1'
    tty: true

  # Deuxième client - Ajoute et retire des tâches automatiquement
  c2:
    container_name: arret05-c2
    image: arret05-client
    depends_on:
      - s1
    environment:
      - MONSERVEUR='s1'
      - MONNOM='c2'
    tty: true

  # Troisième client - Ajoute et retire des tâches automatiquement
  c3:
    container_name: arret05-c3
    image: arret05-client
    depends_on:
      - s1
    environment:
      - MONSERVEUR='s1'
      - MONNOM='c3'
    tty: true

  s1:
    # Serveur unique - Traite les demandes todo
    build:
      context: .
      dockerfile: Dockerfile.serveur      
    container_name: arret05-s1
    image: arret05-serveur
    tty: true
    depends_on:
      - db
  # Permet d'observer les tâches en cours
  gestionnaire:
    build: 
      context: .
      dockerfile: Dockerfile.gestionnaire
    container_name: arret05-gestionnaire
    image: a5-gestionnaire
    tty: true
    environment:
      MONSERVEUR: s1
      MONNOM: c1,c2,c3

    depends_on:
      - s1

  # Permet d'enregistrer les tâches
  db:
    container_name: arret05-db
    image: postgres:15
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DATABASE: 'postgres'
    #ports:
    #  - 5435:5432
    #environment:
    #  - POSTGRES_PASSWORD=postgres
    #  - POSTGRES_USER=postgres
    #  - POSTGRES_DB=postgres
    volumes:
      - "todo-db:/var/lib/postgresql/data"
      - "./init_db/sql:/docker-entrypoint-initdb.d/init.sql"

volumes:
  todo-db:

# Réseau par défaut
networks:
  arret05-todo-net:
